# Generated by Django 4.2.2 on 2023-06-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_profile', '0002_remove_profile_bio_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.CharField(blank=True, default='/imgs/default_avatar.png', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other'), (4, 'Prefer not to say')], null=True),
        ),
    ]
