# Generated by Django 4.2.2 on 2023-06-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_profile', '0003_alter_profile_avatar_url_alter_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website_url',
        ),
    ]
