# Generated by Django 4.2.2 on 2023-06-29 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_profile', '0004_remove_profile_avatar_url_remove_profile_website_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
    ]
